name: dr
channels:
  - defaults
dependencies:
  - python=3.8
  - absl-py
  - pyparsing
  - pip
  - pip:
    - torch
    - torchvision
    - wandb
    - matplotlib
    - configargparse
    - scipy
    - ipdb
    - wandb
    - tensorboard
    - tqdm